### PR TITLE
fix(serenity-bdd): escape html tags in scenario names

### PR DESCRIPTION
**Pull request by jan-molak**

### CODE REVIEW

**Comment by jan-molak** [comment]
@viper3400 - I wonder if we should approach this from a different angle; rather than changing the scenario title to avoid the report getting truncated, perhaps it would be better to ensure Serenity/JS escapes any HTML tags before producing a Serenity BDD JSON report.

I can imagine other people having HTML or XML tags in scenario titles (especially if they're interacting with XML APIs or some such).

What do you think?

**Comment by jan-molak** [comment]
Looks like OpenPGP is down, and CodeClimate has a dependency on it...

```
Error: network timeout at: https://keys.openpgp.org/vks/v1/by-fingerprint/9BD9E2DD46DA965A537E5B0A5CBF320243B6FD85
Error: 🚨 CC Reporter GPG signature verfication failed!
```
They also have a typo in their error message...

**Comment by viper3400** [comment]
@jan-molak , escaping sounds reasonable. Fixing the test description was just my shorthand because I wanted to have a look at the failing `Page.spec` - but found the report was nearly empty.

As you've already solved it looks like it was not too much effort. 👍

**Comment by jan-molak** [comment]
I'm glad you found this bug, I want aware of it 👍

**Review by viper3400 — APPROVED** [review]

**Pull request merged**
