### PR TITLE
feat(schematics): adds schematics to install serenity-js for cucumber/protractor and scaffold initial files

### PR DESCRIPTION
**Pull request by cmurczek-it**
this schematic provides setup of serenity with protractor/cucumber. it installs all required
dependencies, configures protractor and scaffolds the code files for actors and cucumber timeouts.
the schematic accepts parameters for selecting the testingFramework (currently only cucumber),
browserIntegration (currently only protractor) as well as the (angular) project name to which
serenity should be added (defaults to the project set as defaultProject)
and a directory to use for the e2e testing code (defaults to features).

I'll add some more configuration options (e.g. cucumber version). I'm also thinking about adding generate-schematcs for, e.g. step-defs, targets, etc. as well as support for Mocha/Jasmine. @jan-molak any thoughts on priorities? Should I create separate PRs or would you prefer to keep this one open?

 #359

<a href="https://gitpod.io/#https://github.com/serenity-js/serenity-js/pull/591"></a>

### CODE REVIEW

**Comment by jan-molak** [comment]
Hey @cmurczek! This is awesome, thanks so much for picking it up :-)

Do you think it would be possible to move integration with schematics to a separate package, outside of `@serenity-js/core`? I'm trying to keep the core agnostic of frameworks and execution environments.

**Comment by cmurczek** [comment]
Hi @jan-molak, sure makes sense.
The cli command for adding a package/lib to an angular project is to run `ng add <packagename>`. To that effect the schematic must be published as part of the npm-package. The schematic itself, however, is not not really tied to the package. It must for example be transpiled separately, after the package itself. The output dir is controlled in a separate tsconfig. The schematic code is outside the root dir of the package. It's more like the schematic is piggybacking on the package to allow the angular cli to invoke the install scripts by looking the package up in the npm registry.

So when moving it out of the core-package, how should the package be called? Just `serenity-js` so that one would run `ng add serenity-js`, or _@serenity-js/schematics_, similar to what ngrx does?

**Comment by jan-molak** [comment]
`serenity-js` is the old (1.x) version of the framework some people are still using, let's go with `@serenity-js/schematics`. Thanks!

**Comment by cmurczek** [comment]
@jan-molak I migrated the schematic into a separate package (@serenity-js/schematics). Would you rather have installation support for jasmine and mocha, resp different cucumber versions next, or should I look into generation of spec files and screenplay pattern building blocks (targets, tasks, interactions, questions)?

**Comment by jan-molak** [comment]
Thanks! It might be better to have a full vertical slice working first, so I'd vote for Serenity/JS + latest version of Cucumber + Screenplay 👍 

Don't worry about supporting older versions of Cucumber, we should encourage people to use the latest and greatest for new projects :-)

**Comment by jan-molak** [comment]
Hey @cmurczek-it, and apologies for taking so long to get back to you! As I hope you can understand, I was focusing on getting Serenity/JS v3 finished and released and it's taken a while.

Are you still interested in working on adding support for Angular Schematics or Nx for Serenity/JS v3? I now have the capacity to help you get it merged.

**Comment by jan-molak** [comment]
Closing as Protractor has reached its end-of-life. Happy to collaborate with you on other Serenity/JS features, though, @cmurczek-it!

**Pull request closed without merging**
