### PR TITLE
test(web): changed description in Page spec

### PR DESCRIPTION
**Pull request by viper3400**
SerenityBDD report was not able to show descriptions that contain HTML tags like \<title/\>

### CODE REVIEW

**Comment by viper3400** [comment]
grafik

**Comment by viper3400** [comment]
@jan-molak , not sure, why the Main/Coverage job fails!?

**Comment by jan-molak** [comment]
Not sure, I'll take a look

**Comment by jan-molak** [comment]
I think the coverage:publish check fails because it doesn't have access to the CodeClimate token. And it doesn't have access because [GitHub doesn't give PRs access](https://github.com/orgs/community/discussions/26242) to the main repo tokens.

Now, interestingly enough, CodeClimat claims that this token is only ever used to identify the repository, so [doesn't have to be secret](https://docs.codeclimate.com/docs/finding-your-test-coverage-token)

**Comment by viper3400** [comment]
see #1631

**Pull request closed without merging**
