### PR TITLE
feat(web): implemented possibility to enter sensitive data 

### PR DESCRIPTION
**Pull request by viper3400**
implemented possibility to enter sensitive data not visible in the report

Related tickets: #2165

### CODE REVIEW

**Comment by jan-molak** [comment]
Nice one, @viper3400! Thanks for picking it up :+1: 
I'd suggest to keep the concept of masking separate from `Enter` as this way folks will be able to reuse it with other interactions that require text input, such as sending a HTTP request with an auth token. 

I like the name `Masked` you propose in the PR, have you considered introducing a question like `Masked.valueOf(parameter: Answerable<string>)`? We could add it to [`@serenity-js/core:screenplay/questions`](https://github.com/serenity-js/serenity-js/tree/main/packages/core/src/screenplay/questions) perhaps?

**Comment by viper3400** [comment]
@jan-molak , yes, maybe that's the better approach. My proposal was more or less just a quick hack. Can try to implement Question instead, as it was the initial proposal from @eyesopen, anyway.

Though, it then will be not that obvious, how to solve the problem of masking passwords in the `Enter`. We've to describe this than a bit more verbose in the relevant places I guess.

**Comment by jan-molak** [comment]
> Though, it then will be not that obvious, how to solve the problem of masking passwords in the Enter. We've to describe this than a bit more verbose in the relevant places I guess.

Yeah, I think we should. We could add an example in `Enter` api docs:

```
Enter.theValue(Masked.valueOf('Password')).into(..)
```

**Comment by viper3400** [comment]
Okay, added a `Masked` class into core package. Still have to add some documentation and maybe some test in the core package itself. 

I let the test in the web-specs integration package be. I think it's a good place to test integration and a good documentation for someone who wants to learn from the tests.

Any other place I should add tests?

**Comment by viper3400** [comment]
This is what I came up with so far. Please review.

**Comment by jan-molak** [comment]
Looks great, I added some very minor suggestions around the wording if you have 5 minutes to push them. If not, that's cool too; I can make them myself when merging.

**Comment by viper3400** [comment]
I cannot find you suggestions?! Should it be review comments?

**Comment by jan-molak** [comment]
Schoolboy error, I forgot to click on submit 🤦🏻‍♂️

**Comment by viper3400** [comment]
> Schoolboy error, I forgot to click on submit 🤦🏻‍♂️

Happens the best ... 😬

**Comment by viper3400** [comment]
I think, it is done.

**Comment by viper3400** [comment]
@jan-molak , something missing in here?

**Comment by jan-molak** [comment]
Hey @viper3400 - no, it's all good, I'll get it merged with other outstanding PRs. Thanks!

**Pull request merged**
