### PR TITLE
fix(integration): adjusted some test time-outs

### PR DESCRIPTION
**Pull request by viper3400**
Hi @jan-molak, I had some troubles and ran into time-outs on my Windows machine.

### CODE REVIEW

**Comment by viper3400** [comment]
As I wrote at Gitter, this PR is still marked as draft as I struggle with timeouts and the parallel execution of the tests on my local machine.

**Comment by jan-molak** [comment]
Hey @viper3400, I've made a number of adjustments around parallel execution on the [`features/web`](https://github.com/serenity-js/serenity-js/tree/features/web) branch so would be grateful if you could check it out and run the build to see if you're still getting timeouts?

**Comment by viper3400** [comment]
Hi @jan-molak , thanks for that. I will check as soon as possible and provide feedback.

**Comment by viper3400** [comment]
Hi @jan-molak , I tried yesterday evening but got timeouts and errors. Tried some tweaks today, and got other timeouts and errors at later stages.

Kind of funny: I now found the same solution you found 4 hours before: https://github.com/serenity-js/serenity-js/blame/31059638ab1a759581d5872b8e75aa315d8096f4/package.json#L31 😄 

I think, this concurrency thing is a match. I will test with your latest commit.

But anyway, I think I still struggle with some timeouts in the "unit" tests that run before the integration part. I will see, if I get this running and prepare some changes probably.

By the way is this [allScriptsTimeout: 120_000,](https://github.com/serenity-js/serenity-js/blob/31059638ab1a759581d5872b8e75aa315d8096f4/integration/web-protractor-runner/src/protractor.conf.ts#L25) and this [timeout: 60_000,](https://github.com/serenity-js/serenity-js/blob/31059638ab1a759581d5872b8e75aa315d8096f4/integration/web-protractor-runner/src/protractor.conf.ts#L44) intended? Never saw this syntax before!? Is this a typo or something to I can learn?

**Comment by jan-molak** [comment]
> Kind of funny: I now found the same solution you found 4 hours before: https://github.com/serenity-js/serenity-js/blame/31059638ab1a759581d5872b8e75aa315d8096f4/package.json#L31 😄

> I think, this concurrency thing is a match. I will test with your latest commit.

Cool, give it a try and let me know how it goes. Turns out that Lerna has slightly [exotic conventions](https://github.com/lerna/lerna/issues/1948#issuecomment-468354267) for CLI switches 🤷🏻‍♂️ 

>  Never saw this syntax before!? Is this a typo or something I can learn?

Those are [numeric separators](https://v8.dev/features/numeric-separators)

**Comment by viper3400** [comment]
@jan-molak , lets go step by step:  I pushed a new change. This is the timeout from cucumber tests, which definitely hinders the local test & build on my side. This PR is now based on your ```feature/web``` branch. But I think, this would apply to the ```main``` aka ```master``` branch as well.

> Those are numeric separators, supported from Node 12.5.0, that we can use now that we've dropped support for EOL Node 10.

Okay, got me! Never heard this before, but it's never to late .... But actually, I just stumbled over this topic, just because my integration tests fail exactly at this point ... and if I remove the underscore, all will be fine. 

So I'm on node 12.18.4 ... Though this is above the 12.5.0 you've mentioned, this is may not be the latest piece of art, I suppose 👴. I will try to update this and have another try.

But main point in here is: I _am_ able to run the tests now without errors on my local Windows 10. 👍 

I would appreciate if you'd consider to merge the change from the current PR, anyway. I think every fix in this timeout topic will make it easier to contribute for other people, as well.

PS: Is there a reason why you don't fix the CodeFactor issues in the Github build? (out of that you haven't had time to do it or that if had have no priority, at all?)

**Comment by jan-molak** [comment]
Nice one, thanks!

> PS: Is there a reason why you don't fix the CodeFactor issues in the Github build? (out of that you haven't had time to do it or that if had have no priority, at all?)

Nah, I wanted to speed up the Windows build in the pipeline first because it's really bothering me how long it takes. I'll have a look into CodeFactor next, thanks. Unless you want to take a quick stab at it?

**Comment by viper3400** [comment]
@jan-molak : I fixed the CodeFactor issues. One was just a trailing whitespace, the other was [this one] (https://www.codefactor.io/repository/github/serenity-js/serenity-js/pull/987). Obviously you don't need the left padding, when it is the same value as the right padding.

The release pipeline did not start for the last push, anyway.

**Comment by viper3400** [comment]
@jan-molak : As written in the gitter chat I had to increase other timeouts in ```integration/webdriverio-jasmine```. I updated my branch.

**Comment by jan-molak** [comment]
Nice one, thanks!

**Pull request merged**
