### PR TITLE
feat - 2.0 alert support

### PR DESCRIPTION
**Pull request by nbarrett**
Second attempt at creating a PR for this branch as I think the [last one](https://travis-ci.org/jan-molak/serenity-js/builds/613765891?utm_medium=notification&utm_source=github_status) got broken as I force-pushed my subsequent changes 🤞

### CODE REVIEW

**Comment by nbarrett** [comment]
Hi @jan-molak - I've been testing this code locally with my application and it seems like I am hitting up against the same problem that I originally encountered with [https://github.com/jan-molak/serenity-js/issues/65](issue #65), so I think that the [error handling that was added to the 1.x photographer](https://github.com/jan-molak/serenity-js/blob/6e374193ec5bc7e015246b0a8c83ee429c2bd8d3/packages/serenity-js/src/serenity-protractor/stage/photographer.ts#L139) might need to be migrated to version 2.0 as well. Shall I have a go at this?

**Comment by nbarrett** [comment]
Hmmm...Latest build is failing with [NoSuchAlertError: no such alert](https://travis-ci.org/jan-molak/serenity-js/jobs/621508249#L1596)
```
@serenity-js/protractor: (node:8720) UnhandledPromiseRejectionWarning: NoSuchAlertError: no such alert
@serenity-js/protractor:   (Session info: headless chrome=78.0.3904.108)
@serenity-js/protractor:   (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Linux 4.15.0-1028-gcp x86_64)
@serenity-js/protractor:     at Object.checkLegacyResponse (/home/travis/build/jan-molak/serenity-js/node_modules/selenium-webdriver/lib/error.js:546:15)
@serenity-js/protractor:     at parseHttpResponse (/home/travis/build/jan-molak/serenity-js/node_modules/selenium-webdriver/lib/http.js:509:13)
@serenity-js/protractor:     at doSend.then.response (/home/travis/build/jan-molak/serenity-js/node_modules/selenium-webdriver/lib/http.js:441:30)
@serenity-js/protractor:     at <anonymous>
@serenity-js/protractor:     at process._tickCallback (internal/process/next_tick.js:189:7)
@serenity-js/protractor: (node:8720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

And then later on other specs are failing with [UnexpectedAlertOpenError: unexpected alert open: {Alert text : Press OK or Cancel}](https://travis-ci.org/jan-molak/serenity-js/jobs/621508249#L1642)

```
Browser
@serenity-js/protractor:        returns no entries if the console log is empty:
@serenity-js/protractor:      UnexpectedAlertOpenError: unexpected alert open: {Alert text : Press OK or Cancel}
@serenity-js/protractor:   (Session info: headless chrome=78.0.3904.108)
```

So I'm a but stumped really and need some help please @jan-molak. Also I see this error when I try and run the protractor tests locally:

```
> @serenity-js/protractor@2.0.1-alpha.88 test /Users/nick/dev/git-personal/serenity-js/packages/protractor
> nyc --report-dir ../../target/coverage/protractor protractor ./spec/protractor.conf.js

[09:25:24] I/launcher - Running 1 instances of WebDriver
[09:25:24] I/direct - Using ChromeDriver directly...
[09:25:27] E/launcher - Error: Error: Cannot find module 'is-plain-object'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```

Again, I'm a but stumped about that one!

**Comment by mtahat** [comment]
I am having the same issue, I was able to accept the alert but the ScreenShot failed ( I am taking screenshot on each interaction). that causing the whole test to break! is there any workaround to fix the screenshot exception? are you guys expecting this pull request to be merged soon?

**Comment by nbarrett** [comment]
Hiya @mtahat and @jan-molak  - gosh lots has changed since I created this PR. I'll give this a rebase and then see what happens with the tests and then take it from there? Would be great to get this merged as I still have a local version of [BrowseTheWeb](https://github.com/serenity-js/serenity-js/blob/master/packages/protractor/src/screenplay/abilities/BrowseTheWeb.ts) in my "working" project that I'd like to lose :-)

**Comment by nbarrett** [comment]
Hi @jan-molak - I've rebased and cleaned up this PR and await your review and merge 👍

**Comment by jan-molak** [comment]
Thanks @nbarrett, I'll review it shortly!

**Comment by nbarrett** [comment]
🎉  👍  Cheers @jan-molak - serenity-js has Alert support! (actually they matured into ModalDialogs)

**Pull request closed without merging**
