### PR TITLE
More strictness of @issue tag.

### PR DESCRIPTION
**Pull request by fparmu**
Since we got @known_issues as a tag, we cannot run those tests because this regular expression is too soft.

### CODE REVIEW

**Comment by jan-molak** [comment]
Nice catch, thanks @fparmu!

Could you please also add [tests around it](https://github.com/serenity-js/serenity-js/blob/master/packages/core/spec/model/Tag.spec.ts) so that it doesn't regress in the future?

**Comment by fparmu** [comment]
Of course, here you have it. Please let me know if this one case is enough for you. :)

**Comment by jan-molak** [comment]
That's perfect, thanks!

**Comment by jan-molak** [comment]
Released in 2.25.3, thanks for your contribution @fparmu

**Pull request closed without merging**
